In [16]:
import pandas as pd
import snowflake.connector
# import sqlalchemy
# from sqlalchemy import create_engine
# import sqlalchemy
# from snowflake.sqlalchemy import URL
# import teradata_sqlalchemy
import datetime
import teradata
import re
import timeit
import getpass

pyinstaller openpyxl workaround

https://stackoverflow.com/questions/74303354/converted-py-to-exe-using-pyinstaller-but-when-run-it-getting-openpyxl-module-mi

command line = pyinstaller -c <.py file> --hidden-import="openpyxl.cell._writer" --hidden-import="snowflake.connector.snow_logging"

In [17]:
start = timeit.default_timer()

In [4]:
username = input('Nike Username: ')
password = getpass.getpass('Password: ')

In [5]:
# Gets the version
ctx = snowflake.connector.connect(
    user = username,
    password = password,
    account = 'nike',
    authenticator = 'externalbrowser'
    )
cs = ctx.cursor()
try:
    cs.execute("SELECT current_version()")
    one_row = cs.fetchone()
    print(one_row[0])
finally:
    cs.close()
ctx.close()

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://nike.okta.com/app/snowflake/exk3gsxh1ykZ4xX5b1t7/sso/saml?SAMLRequest=jZLdctowEIVfxaNeY8mOQ4MGyBAoxU1KmEDaTO6EvRjFtuRq5Rj69JX56aQXyfROI52jb3fP9q93ZeG9gkGp1YAEPiMeqESnUmUD8riadq6Ih1aoVBRawYDsAcn1sI%2BiLCo%2Bqu1WPcCvGtB67iOFvH0YkNoorgVK5EqUgNwmfDn6fsdDn3GBCMY6HDlZUpSOtbW24pQ2TeM3F742GQ0ZY5T1qFO1kk%2FkDaL6mFEZbXWii7Nl53p6BxFQFrUIp3CExcl4I9VxBB9R1kcR8tlqtegs7pcr4o3O3Y21wroEswTzKhN4fLg7FoCugnl8%2B8VHpZtNIXJIdFnV1n3kuxPdQEoLnUk3nngyIFUu0324Zyb6WZswDrov95uXzTqbrb%2FOnr5Ne3EC89Hv2biM8tvshiXE%2B3EOM2zDjBFriFUboXVXLIw6LOoE3VUYcNbll12%2Fd9V9Jt7ERSiVsAfnuU4lc%2FB1bsWhMlFV9G%2FRFHb5RYa7bbDPn6Pd0%2BU6sJ8poqZtPOS4IfxAN8P%2F6LtP3xpO%2BzV3I48nC13IZO9NtSmFfT%2BRwA8ONzLtbA5SDqWQxShNDSC6ZIpCN2MDwro1tqYGQodH6r%2BLPPwD&RelayState=50282 to authenticate...
8.14.2

In [18]:
credentials = {
        "account" :"nike",
        "user" : username,
        "password" :password,
        # "database" :"DA_DSM_SCANALYTICS_PROD",
        "database" :"DA_DSM_SCANALYTICS_PROD",
        "warehouse" :"DA_DSM_SCANALYTICS_REPORTING_PROD",
        "schema" : "PROCESSED",
        # "role":"MPAA_ROLE_PROD_ANALYTICS",
        "role":"Application_SnowFlake_Prod_DSM_SCANALYTICS_Read",
        "auth": "externalbrowser",
        "authenticator" : "https://nike.okta.com"
    }

In [19]:
#JSON Linked file to setup username, password, and other database details
def create_sql_engine(credentials):

    # engine = create_engine(URL(
    engine = snowflake.connector.connect(

        account=credentials['account'],
        user=credentials['user'],
        password=credentials['password'],
        database=credentials['database'],
        warehouse=credentials['warehouse'],
        schema=credentials['schema'],
        role=credentials['role'],
        authenticator=credentials['auth'],

    )
    return engine
    
# engine = create_sql_engine("credentials.json")
engine = create_sql_engine(credentials)

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://nike.okta.com/app/snowflake/exk3gsxh1ykZ4xX5b1t7/sso/saml?SAMLRequest=jZJfb9owFMW%2FSuQ9J3ZCGMMiVLS0W0bXohKmqW8mMcGKY6e%2BTgPfvg5%2Fpu6h1d4s%2Bxz%2F7r3nTq72tfReuQGhVYLCgCCPq1wXQpUJWmd3%2FjfkgWWqYFIrnqADB3Q1nQCrZUNnrd2pJ%2F7ScrCe%2B0gB7R8S1BpFNQMBVLGaA7U5Xc1%2B3dMoIJQBcGMdDp0tBQjH2lnbUIy7rgu6QaBNiSNCCCZj7FS95At6h2g%2BZzRGW51rebHsXU8fIEJM4h7hFI6wPBuvhTqN4DPK5iQC%2BiPLlv7ycZUhb3bp7kYraGtuVty8ipyvn%2B5PBYCr4CFd3AagdLeVrOK5rpvWuo8Cd8JbXmCpS%2BHGk84T1FSiiL9vmoVks58L%2BxJZeV3mTG2Gcm3LwUHAaBix3eNtSNL5ap0j7%2FclzKgPMwVoear6CK27IlHsk9gPv2ZRSMmIRuOAjEfPyJu7CIVi9ui81KlExQNdWXasjDUN%2Fls05vtqUMJ%2BFx6q53j%2FZ7gJ7QgDaNzHg04bQo90M%2F2Pvif4veG8Xw9u5Ol8qaXID96dNjWzHycSBuHxRhT%2B9iilvGZCzorCcACXjJS6uzGcWbfG1rQc4emJ%2Bu8iT98A&RelayState=50344 to authenticate...

In [20]:
# SQL queries

# https://confluence.nike.com/display/EDAEDP/Global+Product+Line

gel_query = """

SELECT
SEASON_YEAR_DESCRIPTION AS seasn_yr_cd,
DIVISION_CODE AS DIV_CD,
STYLE_NUMBER AS styl_dsply_cd,
DEVELOPMENT_TEAM_NAME

FROM EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1

WHERE 
DIVISION_CODE IN (10, 20)
and SEASON_YEAR_DESCRIPTION IN {}
and (DEVELOPMENT_TEAM_NAME like '%GEL%' or DEVELOPMENT_TEAM_NAME like '%GLOBAL EXPRESS%')
and STYLE_NUMBER is not null

GROUP BY 
SEASON_YEAR_DESCRIPTION, DIVISION_CODE, STYLE_NUMBER, DEVELOPMENT_TEAM_NAME

        """

biz_season_query = """

select 
        BUSALTSEASNCD
        ,BUSSEASNSTRTDT
        ,BUSSEASNENDDT
        ,BUSSEASNSORTSEQNBR
from NGP_DA_PROD.PLN.CAL_BUSFSCLN1GREGORIANCALDT_V
where BUSCALCD = 'NF'
group by 1,2,3,4
order by BUSSEASNSORTSEQNBR
        
        """

max_engine_run_dt_query = """
SELECT 
max(REF_SNP_ENGN_RUN_DT)
FROM DA_DSM_SCANALYTICS_PROD.INTEGRATED.UNPLANNED_T

        """

In [21]:
#SQL Engine to read the four queries, run one at a time if on local machine	
# df_season = pd.read_sql_query(biz_season_query, engine)
# df_season = df_season.sort_values(by=['curr_bus_seasn_ofst_nbr'])
# display(df_season)

sf = engine.cursor()
seasn_query = sf.execute(biz_season_query)

headers = [i[0] for i in sf.description]

df_season = pd.DataFrame(seasn_query.fetchall())
# df_season.columns = [headers]
# df_season = df_season.sort_values(by = ['CURR_BUS_SEASN_OFST_NBR'])
# df_season = df_season.sort_values(by = [3])
display(df_season)

          0           1           2    3
0    SU1999  1999-06-01  1999-06-30    1
1    FA1999  1999-07-01  1999-09-30    2
2    HO1999  1999-10-01  1999-12-31    3
3    SP2000  2000-01-01  2000-03-31    4
4    SU2000  2000-04-01  2000-06-30    5
..      ...         ...         ...  ...
140  SU2034  2034-04-01  2034-06-30  141
141  FA2034  2034-07-01  2034-09-30  142
142  HO2034  2034-10-01  2034-12-31  143
143  SP2035  2035-01-01  2035-03-31  144
144  SU2035  2035-04-01  2035-06-30  145

[145 rows x 4 columns]

In [22]:
today = datetime.date.today()
print(today)

2024-04-16

In [23]:
def cur_date(date_today):
    return df_season[(date_today >= df_season[1]) & (date_today <= df_season[2])]

def seasons(date_today):
    cur_season = cur_date(date_today)
    cur_season_val = cur_season[3].values[0]
    result_df = df_season[(df_season[3] > cur_season_val) & (df_season[3] <= cur_season_val + 4)]
    result_list = result_df[0].values.tolist()
    t = tuple(result_list)
    return gel_query.format(t)
     
seasons(today)

"\n\nSELECT\nSEASON_YEAR_DESCRIPTION AS seasn_yr_cd,\nDIVISION_CODE AS DIV_CD,\nSTYLE_NUMBER AS styl_dsply_cd,\nDEVELOPMENT_TEAM_NAME\n\nFROM EDA_PRODUCT_PROD.BCL_PRODUCT_LINE.GLOBAL_PRODUCT_LINE_V1\n\nWHERE \nDIVISION_CODE IN (10, 20)\nand SEASON_YEAR_DESCRIPTION IN ('FA2024', 'HO2024', 'SP2025', 'SU2025')\nand (DEVELOPMENT_TEAM_NAME like '%GEL%' or DEVELOPMENT_TEAM_NAME like '%GLOBAL EXPRESS%')\nand STYLE_NUMBER is not null\n\nGROUP BY \nSEASON_YEAR_DESCRIPTION, DIVISION_CODE, STYLE_NUMBER, DEVELOPMENT_TEAM_NAME\n\n        "

In [24]:
# df_gel = pd.read_sql_query(seasons(today), engine)
sf_gel_query = sf.execute(seasons(today))
df_gel = pd.DataFrame(sf_gel_query.fetchall())
display(df_gel)

           0   1       2           3
0     FA2024  10  HM0180  GEL - EMEA
1     HO2024  10  HV5046    GEL - NA
2     FA2024  10  FZ6809  GEL - APLA
3     FA2024  20  FZ5051    GEL - GC
4     FA2024  10  HQ2483    GEL - NA
...      ...  ..     ...         ...
2547  FA2024  20  FQ6477  GEL - APLA
2548  FA2024  10  HF5208    GEL - NA
2549  SP2025  20  IB4620    GEL - GC
2550  SP2025  20  HV4367  GEL - APLA
2551  FA2024  20  DR7852    GEL - GC

[2552 rows x 4 columns]

In [25]:
ap_headers = ['PPPriorityID','Plant','DemandSeason','CategoryDesc','SubCategoryDesc','LeagueID','LeagueDesc','StyleCode','ColorCode','PriorityDesc','Reason','RequestedBy','Priority','DefaultPriority','updFlag','Error']

fw_headers = ['PPPriorityID','Plant','DemandSeason','CategoryDesc','SubCategoryDesc','StyleCode','ColorCode','Reason','RequestedBy','PriorityDesc','Priority','DefaultPriority','updFlag','Error']

gel_ap_template = pd.DataFrame(columns=ap_headers)
gel_fw_template = pd.DataFrame(columns=fw_headers)

df_gel_ap = df_gel[df_gel[1] == '10']
df_gel_fw = df_gel[df_gel[1] == '20']

gel_ap_template['DemandSeason'] = df_gel_ap[0]
gel_ap_template['StyleCode'] = df_gel_ap[2]
gel_ap_template['PriorityDesc'] = 'P'
gel_ap_template['Reason'] = 'GEL'
gel_ap_template['RequestedBy'] = 'GOVERNANCE STANDARD'
gel_ap_template['Priority'] = '50'
gel_ap_template['DefaultPriority'] = '100'
gel_ap_template['updFlag'] = "I"

gel_fw_template['DemandSeason'] = df_gel_fw[0]
gel_fw_template['StyleCode'] = df_gel_fw[2]
gel_fw_template['PriorityDesc'] = 'P'
gel_fw_template['Reason'] = 'GEL'
gel_fw_template['RequestedBy'] = 'GOVERNANCE STANDARD'
gel_fw_template['Priority'] = '50'
gel_fw_template['DefaultPriority'] = '100'
gel_fw_template['updFlag'] = "I"


display(gel_fw_template)

,PPPriorityID,Plant,DemandSeason,CategoryDesc,SubCategoryDesc,StyleCode,ColorCode,Reason,RequestedBy,PriorityDesc,Priority,DefaultPriority,updFlag,Error
3,NaN,NaN,FA2024,NaN,NaN,FZ5051,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
12,NaN,NaN,HO2024,NaN,NaN,HQ3219,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
14,NaN,NaN,HO2024,NaN,NaN,HV2524,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
20,NaN,NaN,FA2024,NaN,NaN,DZ2791,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
21,NaN,NaN,HO2024,NaN,NaN,DX2657,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546,NaN,NaN,SP2025,NaN,NaN,IB4654,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
2547,NaN,NaN,FA2024,NaN,NaN,FQ6477,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
2549,NaN,NaN,SP2025,NaN,NaN,IB4620,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
2550,NaN,NaN,SP2025,NaN,NaN,HV4367,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
2551,NaN,NaN,FA2024,NaN,NaN,DR7852,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN

Teradata connection for Flyknit + Plugs

In [27]:
# max_engine_run_dt = pd.read_sql_query(max_engine_run_dt_query, engine)
mer_query = sf.execute(max_engine_run_dt_query)
max_engine_run_dt = pd.DataFrame(mer_query.fetchall())
max_engine_run_dt[0] = max_engine_run_dt[0].astype(str)
max_engine_run_dt = max_engine_run_dt[0].values[0]
print(max_engine_run_dt)

2024-04-13

In [28]:
# Teradata connection
udaExec = teradata.UdaExec(appName="testconnec", version="1.0", logConsole=False)
session = udaExec.connect(method="odbc", dsn="Teradata_Production", username=username, password=password, authentication="LDAP", driver="TeraProd")

Flyknit + Plugs queries

In [29]:
flyknit_query = """

select 
"Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" "Ver_Wk_Dt" , 
"Div_v"."DivCd" "Prod_Engn_Cd" , 
right("T3"."BusSeasnCd", 2) || left("T3"."BusSeasnCd", 4) "SesnYr" , 
"LnPln_Rptg_v"."StylDsplyCd" "Styl_Dsply_Cd" , 
"LnPln_Rptg_v"."GlblMatlIntntDesc" "Matl_Intnt_Desc" , 
"SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc" "EDP" , 
"LnPln_Rptg_v"."GlblProdtLglLongNm" "APO_Prod_Desc" , 
"LnPln_Rptg_v"."MatlTypeCd" "Matl_Type_Cd" , 
"LnPln_Rptg_v"."PO_DevTeamNm" "PO_Dev_Team_Nm" , 
"LnPln_Rptg_v"."RgnSeasnSpclOfrgTypeDesc" "c10" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."TotDmndQty") "Tot_Rlsd_DP_Qty" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."NetRqmntsQty") "Net_Rqrmnts_Qty" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."TotUnPlndDmndQty") "Tot_Unplanned_Dmnd_Qty" 
 
from ((((
    "PLN"."Cal_SNP_EngnRunDt_v" "Cal_SNP_EngnRunDt_v__Version_" 
        INNER JOIN "PLN"."SNP_FinGdCmphsvUnPlndDtl_v" "SNP_FinGdCmphsvUnPlndDtl_v" on "Cal_SNP_EngnRunDt_v__Version_"."DivCd" = "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" and "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" = "SNP_FinGdCmphsvUnPlndDtl_v"."RefSNP_EngnRunDt") 
        INNER JOIN "PLN"."LnPln_Rptg_v" "LnPln_Rptg_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" = "LnPln_Rptg_v"."GlblDivCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."PlngCtryCd" = "LnPln_Rptg_v"."PlngCtryCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."PlngProdtCd" = "LnPln_Rptg_v"."PlngProdtCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."MatlTypeCd" = "LnPln_Rptg_v"."MatlTypeCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."RgnSeasnMaxSeqNbr" = "LnPln_Rptg_v"."RgnSeasnMaxSeqNbr") 
        INNER JOIN "PLN"."Div_v" "Div_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" = "Div_v"."DivCd") 
        LEFT OUTER JOIN "PLN"."Cal_BusFsclN1GregorianCalDt_v" "T3" on "SNP_FinGdCmphsvUnPlndDtl_v"."BusSeasnRlvncDt" = "T3"."BusDt" and 'NF' = "T3"."BusCalCd" and 'Y' = "T3"."FirstDtOfBusSeasnInd") 
        LEFT OUTER JOIN "PLN"."SNP_EnhcdDmndPrty_v" "SNP_EnhcdDmndPrty_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."EnhcdDmndPrtyCd" = "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyCd"

where "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc" in ('Standard') and lower ("LnPln_Rptg_v"."GlblMatlIntntDesc") like '%' || lower ('FLYKNIT') || '%' and "LnPln_Rptg_v"."MatlTypeCd" in ('FG   ', 'PROJ ') and "Div_v"."DivCd" in ('20   ') and "SNP_FinGdCmphsvUnPlndDtl_v"."RefSNP_EngnRunDt" = DATE '{max_eng_date}' and "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" = DATE '{max_eng_date}'

group by "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt", "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc", "LnPln_Rptg_v"."MatlTypeCd", "LnPln_Rptg_v"."PO_DevTeamNm", "LnPln_Rptg_v"."GlblMatlIntntDesc", "Div_v"."DivCd", "LnPln_Rptg_v"."StylDsplyCd", "LnPln_Rptg_v"."GlblProdtLglLongNm", "LnPln_Rptg_v"."RgnSeasnSpclOfrgTypeDesc", right("T3"."BusSeasnCd", 2) || left("T3"."BusSeasnCd", 4)

"""

plugs_query = """

select 
"Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" "Ver_Wk_Dt" , 
"Div_v"."DivCd" "Prod_Engn_Cd" , 
"SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc" "EDP" , 
"LnPln_Rptg_v"."MO_ExprsLnInd" "MO_Exprs_Ln_Ind" , 
"LnPln_Rptg_v"."StylDsplyCd" "Styl_Dsply_Cd" , 
"LnPln_Rptg_v"."ColrDsplyCd" "Colr_Dsply_Cd" , 
"LnPln_Rptg_v"."PlngProdtCd" "APO_Prod_Cd" , 
"LnPln_Rptg_v"."GlblProdtLglLongNm" "APO_Prod_Desc" , 
"LnPln_Rptg_v"."MatlTypeCd" "Matl_Type_Cd" , 
"LnPln_Rptg_v"."GlblLgDesc" "Lg_Desc" , 
"LnPln_Rptg_v"."GlblPlngProdtGrpDesc" "Glbl_Plng_Prodt_Grp_Desc" , 
"LnPln_Rptg_v"."GlblCatCoreFcsDesc" "Gbl_Cat_Core_Focs_Desc" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."TotDmndQty") "Tot_Rlsd_DP_Qty" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."NetRqmntsQty") "Net_Rqrmnts_Qty" , 
sum("SNP_FinGdCmphsvUnPlndDtl_v"."TotUnPlndDmndQty") "Tot_Unplanned_Dmnd_Qty"

 from (((
    "PLN"."Cal_SNP_EngnRunDt_v" "Cal_SNP_EngnRunDt_v__Version_" 
        INNER JOIN "PLN"."SNP_FinGdCmphsvUnPlndDtl_v" "SNP_FinGdCmphsvUnPlndDtl_v" on "Cal_SNP_EngnRunDt_v__Version_"."DivCd" = "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" and "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" = "SNP_FinGdCmphsvUnPlndDtl_v"."RefSNP_EngnRunDt") 
        INNER JOIN "PLN"."LnPln_Rptg_v" "LnPln_Rptg_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" = "LnPln_Rptg_v"."GlblDivCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."PlngCtryCd" = "LnPln_Rptg_v"."PlngCtryCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."PlngProdtCd" = "LnPln_Rptg_v"."PlngProdtCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."MatlTypeCd" = "LnPln_Rptg_v"."MatlTypeCd" and "SNP_FinGdCmphsvUnPlndDtl_v"."RgnSeasnMaxSeqNbr" = "LnPln_Rptg_v"."RgnSeasnMaxSeqNbr") 
        INNER JOIN "PLN"."Div_v" "Div_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."DivCd" = "Div_v"."DivCd") 
        LEFT OUTER JOIN "PLN"."SNP_EnhcdDmndPrty_v" "SNP_EnhcdDmndPrty_v" on "SNP_FinGdCmphsvUnPlndDtl_v"."EnhcdDmndPrtyCd" = "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyCd"

 where "SNP_FinGdCmphsvUnPlndDtl_v"."RefSNP_EngnRunDt" = DATE '{max_eng_date}' and "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt" = DATE '{max_eng_date}' and "LnPln_Rptg_v"."MatlTypeCd" in ('PLUG ') and "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc" in ('Standard')
 
 group by "Cal_SNP_EngnRunDt_v__Version_"."RefSNP_EngnRunDt", "SNP_EnhcdDmndPrty_v"."EnhcdDmndPrtyDesc", "LnPln_Rptg_v"."MatlTypeCd", "LnPln_Rptg_v"."MO_ExprsLnInd", "LnPln_Rptg_v"."StylDsplyCd", "Div_v"."DivCd", "LnPln_Rptg_v"."ColrDsplyCd", "LnPln_Rptg_v"."PlngProdtCd", "LnPln_Rptg_v"."GlblProdtLglLongNm", "LnPln_Rptg_v"."GlblLgDesc", "LnPln_Rptg_v"."GlblPlngProdtGrpDesc", "LnPln_Rptg_v"."GlblCatCoreFcsDesc"

 order by 2 asc 

"""

In [32]:
import warnings
warnings.filterwarnings("ignore")
df_fly = pd.read_sql(flyknit_query.format(max_eng_date = max_engine_run_dt), session)
# df_fly = pd.read_sql(flyknit_query.format(max_eng_date = '2024-03-30'), session)
display(df_fly.head())

# td = session.cursor()
# fk_query = td.execute(flyknit_query.format(max_eng_date = max_engine_run_dt))
# print(fk_query)
# df_fly = pd.DataFrame(fk_query.fetchall())
# display(df_fly)

Empty DataFrame
Columns: [Ver_Wk_Dt, Prod_Engn_Cd, SesnYr, Styl_Dsply_Cd, Matl_Intnt_Desc, EDP, APO_Prod_Desc, Matl_Type_Cd, PO_Dev_Team_Nm, c10, Tot_Rlsd_DP_Qty, Net_Rqrmnts_Qty, Tot_Unplanned_Dmnd_Qty]
Index: []

In [33]:
df_plug = pd.read_sql_query(plugs_query.format(max_eng_date = max_engine_run_dt), session)
df_plug['Prod_Engn_Cd'] = df_plug['Prod_Engn_Cd'].astype(int)
display(df_plug)

Empty DataFrame
Columns: [Ver_Wk_Dt, Prod_Engn_Cd, EDP, MO_Exprs_Ln_Ind, Styl_Dsply_Cd, Colr_Dsply_Cd, APO_Prod_Cd, APO_Prod_Desc, Matl_Type_Cd, Lg_Desc, Glbl_Plng_Prodt_Grp_Desc, Gbl_Cat_Core_Focs_Desc, Tot_Rlsd_DP_Qty, Net_Rqrmnts_Qty, Tot_Unplanned_Dmnd_Qty]
Index: []

In [34]:
test_plug_df = pd.read_csv('plug_test.csv')
display(test_plug_df)

,Ver_Wk_Dt,Prod_Engn_Cd,EDP,MO_Exprs_Ln_Ind,Styl_Dsply_Cd,Colr_Dsply_Cd,APO_Prod_Cd,APO_Prod_Desc,Matl_Type_Cd,Lg_Desc,Glbl_Plng_Prodt_Grp_Desc,Gbl_Cat_Core_Focs_Desc,Tot_Rlsd_DP_Qty,Net_Rqrmnts_Qty,Tot_Unplanned_Dmnd_Qty
0,NaN,20,NaN,NaN,NaN,NaN,1234,Milse is a promo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,20,NaN,NaN,NaN,NaN,5678,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,20,NaN,NaN,NaN,NaN,91011,left,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,20,NaN,NaN,NaN,NaN,1213,right,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,20,NaN,NaN,NaN,NaN,14155,GELLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,20,NaN,NaN,NaN,NaN,16,it's Gel,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,20,NaN,NaN,NaN,NaN,123456,1pmo1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,20,NaN,NaN,NaN,NaN,98864,some pmo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,10,NaN,NaN,NaN,NaN,98865,something gel7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,10,NaN,NaN,NaN,NaN,98866,something gel4 is cool,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,10,NaN,NaN,NaN,NaN,98866,something gel44 is cool,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
def categorize(row):
    prod_desc = row['APO_Prod_Desc'].lower()
    regexp = re.compile(r'(?:^|\W)promo(?:$|\W)|(?:^|\W)pmo(?:$|\W)|(?:^|\W)gel(?:$|\W)|(?:^|\W)gel\d+(?:$|\W)')
    if regexp.search(prod_desc):
        return 'PLUG | GEL / PROMO'
    else:
        return 'PLUG | OTHER'

def assign_priority(row):
    check = row['gel/promo check']
    if check == 'PLUG | GEL / PROMO':
        return '50'
    return '150'

test_plug_df['gel/promo check'] = test_plug_df.apply(lambda row: categorize(row), axis=1)
test_plug_df['gel/promo priority'] = test_plug_df.apply(lambda row: assign_priority(row), axis=1)
display(test_plug_df)

# df_plug['gel/promo check'] = df_plug.apply(lambda row: categorize(row), axis=1)
# df_plug['gel/promo priority'] = df_plug.apply(lambda row: assign_priority(row), axis=1)
# display(df_plug)

,Ver_Wk_Dt,Prod_Engn_Cd,EDP,MO_Exprs_Ln_Ind,Styl_Dsply_Cd,Colr_Dsply_Cd,APO_Prod_Cd,APO_Prod_Desc,Matl_Type_Cd,Lg_Desc,Glbl_Plng_Prodt_Grp_Desc,Gbl_Cat_Core_Focs_Desc,Tot_Rlsd_DP_Qty,Net_Rqrmnts_Qty,Tot_Unplanned_Dmnd_Qty,gel/promo check,gel/promo priority
0,NaN,20,NaN,NaN,NaN,NaN,1234,Milse is a promo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50
1,NaN,20,NaN,NaN,NaN,NaN,5678,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | OTHER,150
2,NaN,20,NaN,NaN,NaN,NaN,91011,left,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | OTHER,150
3,NaN,20,NaN,NaN,NaN,NaN,1213,right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | OTHER,150
4,NaN,20,NaN,NaN,NaN,NaN,14155,GELLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | OTHER,150
5,NaN,20,NaN,NaN,NaN,NaN,16,it's Gel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50
6,NaN,20,NaN,NaN,NaN,NaN,123456,1pmo1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | OTHER,150
7,NaN,20,NaN,NaN,NaN,NaN,98864,some pmo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50
8,NaN,10,NaN,NaN,NaN,NaN,98865,something gel7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50
9,NaN,10,NaN,NaN,NaN,NaN,98866,something gel4 is cool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50
10,NaN,10,NaN,NaN,NaN,NaN,98866,something gel44 is cool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PLUG | GEL / PROMO,50

In [32]:
plug_ap_template = pd.DataFrame(columns=ap_headers)
plug_fw_template = pd.DataFrame(columns=fw_headers)
plug_eq_template = pd.DataFrame(columns=fw_headers)

if len(df_plug) != 0:
    df_plug['gel/promo check'] = df_plug.apply(lambda row: categorize(row), axis=1)
    df_plug['gel/promo priority'] = df_plug.apply(lambda row: assign_priority(row), axis=1)
    # display(df_plug)

    df_plug_ap = df_plug[df_plug['Prod_Engn_Cd'] == 10]
    df_plug_fw = df_plug[df_plug['Prod_Engn_Cd'] == 20]
    df_plug_eq = df_plug[df_plug['Prod_Engn_Cd'] == 30]

# # Apparel plugs
    plug_ap_template['StyleCode'] = df_plug_ap['APO_Prod_Cd']
    plug_ap_template['Reason'] = df_plug_ap['gel/promo check']
    plug_ap_template['PriorityDesc'] = 'P'
    plug_ap_template['Priority'] = df_plug_ap['gel/promo priority']
    plug_ap_template['RequestedBy'] = 'GOVERNANCE STANDARD'
    plug_ap_template['DefaultPriority'] = '100'
    plug_ap_template['updFlag'] = "I"

# # Footwear plugs
    plug_fw_template['StyleCode'] = df_plug_fw['APO_Prod_Cd']
    plug_fw_template['PriorityDesc'] = 'P'
    plug_fw_template['Reason'] = df_plug_fw['gel/promo check']
    plug_fw_template['RequestedBy'] = 'GOVERNANCE STANDARD'
    plug_fw_template['Priority'] = df_plug_fw['gel/promo priority']
    plug_fw_template['DefaultPriority'] = '100'
    plug_fw_template['updFlag'] = "I"

# # Equipment plugs
    plug_eq_template['StyleCode'] = df_plug_eq['APO_Prod_Cd']
    plug_eq_template['PriorityDesc'] = 'P'
    plug_eq_template['Reason'] = df_plug_eq['gel/promo check']
    plug_eq_template['RequestedBy'] = 'GOVERNANCE STANDARD'
    plug_eq_template['Priority'] = df_plug_eq['gel/promo priority']
    plug_eq_template['DefaultPriority'] = '100'
    plug_eq_template['updFlag'] = "I"

# display(plug_eq_template)

In [33]:
display(plug_ap_template)

Empty DataFrame
Columns: [PPPriorityID, Plant, DemandSeason, CategoryDesc, SubCategoryDesc, LeagueID, LeagueDesc, StyleCode, ColorCode, PriorityDesc, Reason, RequestedBy, Priority, DefaultPriority, updFlag, Error]
Index: []

In [34]:
fly_fw_template = pd.DataFrame(columns=fw_headers)

if len(df_fly) != 0:
    fly_fw_template['DemandSeason'] = df_fly['SesnYr']
    fly_fw_template['StyleCode'] = df_fly['Styl_Dsply_Cd']
    fly_fw_template['PriorityDesc'] = 'P'
    fly_fw_template['Reason'] = 'FLYKNIT'
    fly_fw_template['RequestedBy'] = 'GOVERNANCE STANDARD'
    fly_fw_template['Priority'] = '50'
    fly_fw_template['DefaultPriority'] = '100'
    fly_fw_template['updFlag'] = "I"

display(fly_fw_template)

Empty DataFrame
Columns: [PPPriorityID, Plant, DemandSeason, CategoryDesc, SubCategoryDesc, StyleCode, ColorCode, Reason, RequestedBy, PriorityDesc, Priority, DefaultPriority, updFlag, Error]
Index: []

In [35]:
# fw_comb = gel_fw_template.append([fly_fw_template, plug_fw_template], ignore_index=True)
fw_comb = pd.concat([gel_fw_template, fly_fw_template, plug_fw_template], ignore_index=True)
# ap_comb = gel_ap_template.append(plug_ap_template, ignore_index=True)
ap_comb = pd.concat([gel_ap_template, plug_ap_template], ignore_index=True)
eq_comb = plug_eq_template

fw_comb = fw_comb.copy(deep=True)
ap_comb = ap_comb.copy(deep=True)
eq_comb = eq_comb.copy(deep=True)


# eq_comb = pd.DataFrame(columns=fw_headers)
display(fw_comb)

,PPPriorityID,Plant,DemandSeason,CategoryDesc,SubCategoryDesc,StyleCode,ColorCode,Reason,RequestedBy,PriorityDesc,Priority,DefaultPriority,updFlag,Error
0,NaN,NaN,HO2024,NaN,NaN,FQ8830,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
1,NaN,NaN,SP2025,NaN,NaN,HV5180,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
2,NaN,NaN,FA2024,NaN,NaN,HJ7389,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
3,NaN,NaN,HO2024,NaN,NaN,HQ4042,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
4,NaN,NaN,SP2025,NaN,NaN,HV5975,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,NaN,NaN,SP2025,NaN,NaN,CN0149,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
1342,NaN,NaN,HO2024,NaN,NaN,DO2791,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
1343,NaN,NaN,SP2025,NaN,NaN,HV5761,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
1344,NaN,NaN,SU2025,NaN,NaN,DQ7647,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN
1345,NaN,NaN,SP2025,NaN,NaN,IB4004,NaN,GEL,GOVERNANCE STANDARD,P,50,100,I,NaN

In [25]:
def write_excel_file(df, pe):
    path = '''C:\\Users\\mhewi3\\Box\\Global Supply And Inventory\\Global S&IP Operations\\03 SUPPLY\\OPERATIONS\\PARAMETER MANAGEMENT\\EDP - PRIORITY\\AD HOC\\Combined_Weekly_Upload_Templates\\'''
    
    if pe == 'ap':
        writer = pd.ExcelWriter(path + str(today) + '_Apparel_EDP_Upload' + '.xlsx')
        df.to_excel(writer, index=False)
        writer.save()
    elif pe == 'fw':
        writer = pd.ExcelWriter(path + str(today) + '_Footwear_EDP_Upload' + '.xlsx')
        df.to_excel(writer, index=False)
        writer.save()
    elif pe == 'eq' and len(eq_comb) > 0:
        writer = pd.ExcelWriter(path + str(today) + '_Equipment_EDP_Upload' + '.xlsx')
        df.to_excel(writer, index=False)
        writer.save()

write_excel_file(ap_comb, 'ap')
write_excel_file(fw_comb, 'fw')
write_excel_file(eq_comb, 'eq')

In [26]:
print(len(eq_comb))

0

In [27]:
stop = timeit.default_timer()
if len(eq_comb) == 0:
    print('AP/FW Time: ', stop - start)
else:
    print('AP/FW + EQ! Time: ', stop - start)

AP/FW Time:  262.3825453